services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_network

  fastapi_app:
    container_name: fastapi_app
    build: .
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - fastapi_network
    restart: always

volumes:
  postgres_data:

networks:
  fastapi_network:
    external: true
