services:
  mongodb:
    container_name: mongodb
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:data/db
    networks:
      - fastapi_network

  note-management:
    # container_name: fastapi_app - don't set it if you are using scaling
    build: .
    volumes:
      - .:/app
    depends_on:
      - mongodb
    env_file:
      - .env
    expose:
      - "5000" # don't directly map if you are using scaling
    networks:
      - fastapi_network
    restart: always
  

volumes:
  mongodb_data:

networks:
  fastapi_network:
    external: true
