name: Sonarqube Scan

on:
    push:
        branches:
            - main

jobs:
    sonarqube-scan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: Run SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@v1
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            
            - name: SonarQube Quality Gate
              uses: sonarsource/sonarqube-quality-gate-action@v1
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            
