name: Sonarqube Scan

on:
    push:
        branches:
            - main

jobs:
    sonarqube-scan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.11

            - name: Install dependencies
              run: | 
                pip install -r requirements.txt
                pip install pytest pytest-cov
            
            - name: Run test with coverage
              run: |
                pytest -q --maxfail=1 --disable-warnings --cov=src --cov-report=xml

            - name: Run SonarQube Scan
              uses: sonarsource/sonarcloud-github-action@v2
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            