name: Sonarqube Scan

on:
    push:
        branches:
            - main

jobs:
    sonarqube-scan:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0

            - name: Run SonarQube Scan
              uses: sonarsource/sonarcloud-github-action@v2
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            